controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    Tiburon.setImage(img`
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..........fffff.
        ...ccc...ff1bbbf
        ..c1cccccccc1bbf
        ..c113333c1c11bf
        .c11333333cc11bf
        .c11c133331c11bf
        .c111cccc3c11bbf
        .f111111111ffbbf
        .ffcc11bbbbffbf.
        .fbbbbbbbbbbbbf.
        fbdbbbbbbbcbbbc.
        fdbbbbbbccbbbfbc
        fbbfcbbbbbcbbfbc
        fbfdccbbccbbfbbf
        ffddcccbbbccffbf
        .cddcccccccf..ff
        .cddcccccccf....
        ..cdbcccccf.....
        ...cbccccf......
        ....cfccf.......
        ...ffbbdc.......
        ..fbccbddc......
        .fbbcccbdc......
        fbbcffccbc......
        fbff...cbc......
        ff......cc......
        `)
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    Tiburon.setImage(img`
        ...........fffffff...ccfff..........
        ..........fbbbbbbbffcbbbbf..........
        ..........fbb111bbbbbffbf...........
        ..........fb11111ffbbbbff...........
        ..........f1cccc1ffbbbbbcff.........
        ..........ffc1c1c1bbcbcbcccf........
        ...........fcc3331bbbcbcbcccf..ccccc
        ............c333c1bbbcbcbccccfcddbbc
        ............c333c1bbbbbbbcccccddbcc.
        ............c333c11bbbbbccccccbbcc..
        ...........cc331c11bbbbccccccfbccf..
        ...........cc13c11cbbbcccccbbcfccf..
        ...........c111111cbbbfdddddc.fbbcf.
        ............cc1111fbdbbfdddc...fbbf.
        ..............cccfffbdbbfcc.....fbbf
        ....................fffff........fff
        `)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    Tiburon.setImage(img`
        ..........fffcc...fffffff...........
        ..........fbbbbcffbbbbbbbf..........
        ...........fbffbbbbb111bbf..........
        ...........ffbbbbff11111bf..........
        .........ffcbbbbbff1cccc1f..........
        ........fcccbcbcbb1c1c1cff..........
        ccccc..fcccbcbcbbb1333ccf...........
        cbbddcfccccbcbcbbb1c333c............
        .ccbddcccccbbbbbbb1c333c............
        ..ccbbccccccbbbbb11c333c............
        ..fccbfccccccbbbb11c133cc...........
        ..fccfcbbcccccbbbc11c31cc...........
        .fcbbf.cdddddfbbbc111111c...........
        .fbbf...cdddfbbdbf1111cc............
        fbbf.....ccfbbdbfffccc..............
        fff........fffff....................
        `)
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    Tiburon.setImage(img`
        ......cc......ff
        ......cbc...ffbf
        ......cbccffcbbf
        ......cdbcccbbf.
        ......cddbccbf..
        .......cdbbff...
        .......fccfc....
        ......fccccbc...
        .....fcccccbdc..
        ....fcccccccddc.
        ff..fcccccccddc.
        fbffccbbbcccddff
        fbbfbbccbbccdfbf
        cbfbbcbbbbbcfbbf
        cbfbbbccbbbbbbdf
        .cbbbcbbbbbbbdbf
        .fbbbbbbbbbbbbf.
        .fbffbbbb11ccff.
        fbbff111111111f.
        fbb11c3cccc111c.
        fb11c133331c11c.
        fb11cc33333311c.
        fb11c1c333311c..
        fbb1cccccccc1c..
        fbbb1ff...ccc...
        .fffff..........
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        `)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    info.changeScoreBy(1)
    Hamburguesa.setPosition(randint(10, 160), randint(10, 120))
    info.startCountdown(5)
})
let Hamburguesa: Sprite = null
let Tiburon: Sprite = null
scene.setBackgroundColor(9)
Tiburon = sprites.create(img`
    ..........fffcc...fffffff...........
    ..........fbbbbcffbbbbbbbf..........
    ...........fbffbbbbb111bbf..........
    ...........ffbbbbff11111bf..........
    .........ffcbbbbbff1cccc1f..........
    ........fcccbcbcbb1c1c1cff..........
    ccccc..fcccbcbcbbb1333ccf...........
    cbbddcfccccbcbcbbb1c333c............
    .ccbddcccccbbbbbbb1c333c............
    ..ccbbccccccbbbbb11c333c............
    ..fccbfccccccbbbb11c133cc...........
    ..fccfcbbcccccbbbc11c31cc...........
    .fcbbf.cdddddfbbbc111111c...........
    .fbbf...cdddfbbdbf1111cc............
    fbbf.....ccfbbdbfffccc..............
    fff........fffff....................
    `, SpriteKind.Player)
controller.moveSprite(Tiburon)
Hamburguesa = sprites.create(img`
    . . . . c c c b b b b b . . . . 
    . . c c b 4 4 4 4 4 4 b b b . . 
    . c c 4 4 4 4 4 5 4 4 4 4 b c . 
    . e 4 4 4 4 4 4 4 4 4 5 4 4 e . 
    e b 4 5 4 4 5 4 4 4 4 4 4 4 b c 
    e b 4 4 4 4 4 4 4 4 4 4 5 4 4 e 
    e b b 4 4 4 4 4 4 4 4 4 4 4 b e 
    . e b 4 4 4 4 4 5 4 4 4 4 b e . 
    8 7 e e b 4 4 4 4 4 4 b e e 6 8 
    8 7 2 e e e e e e e e e e 2 7 8 
    e 6 6 2 2 2 2 2 2 2 2 2 2 6 c e 
    e c 6 7 6 6 7 7 7 6 6 7 6 c c e 
    e b e 8 8 c c 8 8 c c c 8 e b e 
    e e b e c c e e e e e c e b e e 
    . e e b b 4 4 4 4 4 4 4 4 e e . 
    . . . c c c c c e e e e e . . . 
    `, SpriteKind.Food)
Tiburon.sayText("Tengo Hambre", 2000, false)
Tiburon.setBounceOnWall(true)
